// <auto-generated />
using System;
using DotNetWeek5App.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetWeek5App.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250501192630_SeedClasses")]
    partial class SeedClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetWeek5App.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 1",
                            IsActive = true,
                            Name = "Class 1",
                            PersonCount = 11
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 2",
                            IsActive = true,
                            Name = "Class 2",
                            PersonCount = 12
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 3",
                            IsActive = true,
                            Name = "Class 3",
                            PersonCount = 13
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 4",
                            IsActive = true,
                            Name = "Class 4",
                            PersonCount = 14
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 5",
                            IsActive = true,
                            Name = "Class 5",
                            PersonCount = 15
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 6",
                            IsActive = true,
                            Name = "Class 6",
                            PersonCount = 16
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 7",
                            IsActive = true,
                            Name = "Class 7",
                            PersonCount = 17
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 8",
                            IsActive = true,
                            Name = "Class 8",
                            PersonCount = 18
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 9",
                            IsActive = true,
                            Name = "Class 9",
                            PersonCount = 19
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 10",
                            IsActive = true,
                            Name = "Class 10",
                            PersonCount = 20
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 11",
                            IsActive = true,
                            Name = "Class 11",
                            PersonCount = 21
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 12",
                            IsActive = true,
                            Name = "Class 12",
                            PersonCount = 22
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 13",
                            IsActive = true,
                            Name = "Class 13",
                            PersonCount = 23
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 14",
                            IsActive = true,
                            Name = "Class 14",
                            PersonCount = 24
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 15",
                            IsActive = true,
                            Name = "Class 15",
                            PersonCount = 25
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 16",
                            IsActive = true,
                            Name = "Class 16",
                            PersonCount = 26
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 17",
                            IsActive = true,
                            Name = "Class 17",
                            PersonCount = 27
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 18",
                            IsActive = true,
                            Name = "Class 18",
                            PersonCount = 28
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 19",
                            IsActive = true,
                            Name = "Class 19",
                            PersonCount = 29
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 20",
                            IsActive = true,
                            Name = "Class 20",
                            PersonCount = 30
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 21",
                            IsActive = true,
                            Name = "Class 21",
                            PersonCount = 31
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 22",
                            IsActive = true,
                            Name = "Class 22",
                            PersonCount = 32
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 23",
                            IsActive = true,
                            Name = "Class 23",
                            PersonCount = 33
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 24",
                            IsActive = true,
                            Name = "Class 24",
                            PersonCount = 34
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 25",
                            IsActive = true,
                            Name = "Class 25",
                            PersonCount = 35
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 26",
                            IsActive = true,
                            Name = "Class 26",
                            PersonCount = 36
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 27",
                            IsActive = true,
                            Name = "Class 27",
                            PersonCount = 37
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 28",
                            IsActive = true,
                            Name = "Class 28",
                            PersonCount = 38
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 29",
                            IsActive = true,
                            Name = "Class 29",
                            PersonCount = 39
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 30",
                            IsActive = true,
                            Name = "Class 30",
                            PersonCount = 10
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 31",
                            IsActive = true,
                            Name = "Class 31",
                            PersonCount = 11
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 32",
                            IsActive = true,
                            Name = "Class 32",
                            PersonCount = 12
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 33",
                            IsActive = true,
                            Name = "Class 33",
                            PersonCount = 13
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 34",
                            IsActive = true,
                            Name = "Class 34",
                            PersonCount = 14
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 35",
                            IsActive = true,
                            Name = "Class 35",
                            PersonCount = 15
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 36",
                            IsActive = true,
                            Name = "Class 36",
                            PersonCount = 16
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 37",
                            IsActive = true,
                            Name = "Class 37",
                            PersonCount = 17
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 38",
                            IsActive = true,
                            Name = "Class 38",
                            PersonCount = 18
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 39",
                            IsActive = true,
                            Name = "Class 39",
                            PersonCount = 19
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 40",
                            IsActive = true,
                            Name = "Class 40",
                            PersonCount = 20
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 41",
                            IsActive = true,
                            Name = "Class 41",
                            PersonCount = 21
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 42",
                            IsActive = true,
                            Name = "Class 42",
                            PersonCount = 22
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 43",
                            IsActive = true,
                            Name = "Class 43",
                            PersonCount = 23
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 44",
                            IsActive = true,
                            Name = "Class 44",
                            PersonCount = 24
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 45",
                            IsActive = true,
                            Name = "Class 45",
                            PersonCount = 25
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 46",
                            IsActive = true,
                            Name = "Class 46",
                            PersonCount = 26
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 47",
                            IsActive = true,
                            Name = "Class 47",
                            PersonCount = 27
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 48",
                            IsActive = true,
                            Name = "Class 48",
                            PersonCount = 28
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 49",
                            IsActive = true,
                            Name = "Class 49",
                            PersonCount = 29
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 50",
                            IsActive = true,
                            Name = "Class 50",
                            PersonCount = 30
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 51",
                            IsActive = true,
                            Name = "Class 51",
                            PersonCount = 31
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 52",
                            IsActive = true,
                            Name = "Class 52",
                            PersonCount = 32
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 53",
                            IsActive = true,
                            Name = "Class 53",
                            PersonCount = 33
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 54",
                            IsActive = true,
                            Name = "Class 54",
                            PersonCount = 34
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 55",
                            IsActive = true,
                            Name = "Class 55",
                            PersonCount = 35
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 56",
                            IsActive = true,
                            Name = "Class 56",
                            PersonCount = 36
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 57",
                            IsActive = true,
                            Name = "Class 57",
                            PersonCount = 37
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 58",
                            IsActive = true,
                            Name = "Class 58",
                            PersonCount = 38
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 59",
                            IsActive = true,
                            Name = "Class 59",
                            PersonCount = 39
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 60",
                            IsActive = true,
                            Name = "Class 60",
                            PersonCount = 10
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 61",
                            IsActive = true,
                            Name = "Class 61",
                            PersonCount = 11
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 62",
                            IsActive = true,
                            Name = "Class 62",
                            PersonCount = 12
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 63",
                            IsActive = true,
                            Name = "Class 63",
                            PersonCount = 13
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 64",
                            IsActive = true,
                            Name = "Class 64",
                            PersonCount = 14
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 65",
                            IsActive = true,
                            Name = "Class 65",
                            PersonCount = 15
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 66",
                            IsActive = true,
                            Name = "Class 66",
                            PersonCount = 16
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 67",
                            IsActive = true,
                            Name = "Class 67",
                            PersonCount = 17
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 68",
                            IsActive = true,
                            Name = "Class 68",
                            PersonCount = 18
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 69",
                            IsActive = true,
                            Name = "Class 69",
                            PersonCount = 19
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 70",
                            IsActive = true,
                            Name = "Class 70",
                            PersonCount = 20
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 71",
                            IsActive = true,
                            Name = "Class 71",
                            PersonCount = 21
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 72",
                            IsActive = true,
                            Name = "Class 72",
                            PersonCount = 22
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 73",
                            IsActive = true,
                            Name = "Class 73",
                            PersonCount = 23
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 74",
                            IsActive = true,
                            Name = "Class 74",
                            PersonCount = 24
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 75",
                            IsActive = true,
                            Name = "Class 75",
                            PersonCount = 25
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 76",
                            IsActive = true,
                            Name = "Class 76",
                            PersonCount = 26
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 77",
                            IsActive = true,
                            Name = "Class 77",
                            PersonCount = 27
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 78",
                            IsActive = true,
                            Name = "Class 78",
                            PersonCount = 28
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 79",
                            IsActive = true,
                            Name = "Class 79",
                            PersonCount = 29
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 80",
                            IsActive = true,
                            Name = "Class 80",
                            PersonCount = 30
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 81",
                            IsActive = true,
                            Name = "Class 81",
                            PersonCount = 31
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 82",
                            IsActive = true,
                            Name = "Class 82",
                            PersonCount = 32
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 83",
                            IsActive = true,
                            Name = "Class 83",
                            PersonCount = 33
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 84",
                            IsActive = true,
                            Name = "Class 84",
                            PersonCount = 34
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 85",
                            IsActive = true,
                            Name = "Class 85",
                            PersonCount = 35
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 86",
                            IsActive = true,
                            Name = "Class 86",
                            PersonCount = 36
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 87",
                            IsActive = true,
                            Name = "Class 87",
                            PersonCount = 37
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 88",
                            IsActive = true,
                            Name = "Class 88",
                            PersonCount = 38
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 89",
                            IsActive = true,
                            Name = "Class 89",
                            PersonCount = 39
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 90",
                            IsActive = true,
                            Name = "Class 90",
                            PersonCount = 10
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 91",
                            IsActive = true,
                            Name = "Class 91",
                            PersonCount = 11
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 92",
                            IsActive = true,
                            Name = "Class 92",
                            PersonCount = 12
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 93",
                            IsActive = true,
                            Name = "Class 93",
                            PersonCount = 13
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 94",
                            IsActive = true,
                            Name = "Class 94",
                            PersonCount = 14
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 95",
                            IsActive = true,
                            Name = "Class 95",
                            PersonCount = 15
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 96",
                            IsActive = true,
                            Name = "Class 96",
                            PersonCount = 16
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 97",
                            IsActive = true,
                            Name = "Class 97",
                            PersonCount = 17
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 98",
                            IsActive = true,
                            Name = "Class 98",
                            PersonCount = 18
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 99",
                            IsActive = true,
                            Name = "Class 99",
                            PersonCount = 19
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This is class 100",
                            IsActive = true,
                            Name = "Class 100",
                            PersonCount = 20
                        });
                });

            modelBuilder.Entity("DotNetWeek5App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Password = "1234",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Password = "selimcan",
                            Role = "moderator",
                            Username = "selimcan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
